version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./www:/var/www
    depends_on:
    - php

  php:
    build: ./php
    volumes:
    - ./www:/var/www
    depends_on:
    - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 'Passw0rd?'
    volumes:
    - /crm:/var/opt/mssql
    - ./mssql:/tmp/mssql
    ports:
    - 1433:1433
